# Generated by Django 4.1.3 on 2023-07-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
    ]
